[allowlist]
  description = "Global Allowlist"

  # Ignore based on any subset of the file path
  paths = [
    # Ignore all example certs
    '''\/example.*\.pem$''',
                
    # Ignore anything with the word funkymonkey anywhere in the path
    '''funkymonkey''',

    # Ignore some long path
    '''examples\/some\/long\/path\/server.key$''',
		"ts/console/src/tokens.txt",
		"ts/console/src/readfile.ts"

  ]
        
  # Ignore based on any subset of the line
  regexes = [
    # Ignore lines containing pickles
    '''pickles''',
  ]